		incfile	Art_Sonic_Stand,"Graphics Sonic\Stand",bin,dma_safe
		incfile	Art_Sonic_Wait1,"Graphics Sonic\Wait1",bin,dma_safe
		incfile	Art_Sonic_Wait2,"Graphics Sonic\Wait2",bin,dma_safe
		incfile	Art_Sonic_Wait3,"Graphics Sonic\Wait3",bin,dma_safe
		incfile	Art_Sonic_LookUp,"Graphics Sonic\LookUp",bin,dma_safe
		incfile	Art_Sonic_Walk11,"Graphics Sonic\Walk11",bin,dma_safe
		incfile	Art_Sonic_Walk12,"Graphics Sonic\Walk12",bin,dma_safe
		incfile	Art_Sonic_Walk13,"Graphics Sonic\Walk13",bin,dma_safe
		incfile	Art_Sonic_Walk14,"Graphics Sonic\Walk14",bin,dma_safe
		incfile	Art_Sonic_Walk15,"Graphics Sonic\Walk15",bin,dma_safe
		incfile	Art_Sonic_Walk16,"Graphics Sonic\Walk16",bin,dma_safe
		incfile	Art_Sonic_Walk21,"Graphics Sonic\Walk21",bin,dma_safe
		incfile	Art_Sonic_Walk22,"Graphics Sonic\Walk22",bin,dma_safe
		incfile	Art_Sonic_Walk23,"Graphics Sonic\Walk23",bin,dma_safe
		incfile	Art_Sonic_Walk24,"Graphics Sonic\Walk24",bin,dma_safe
		incfile	Art_Sonic_Walk25,"Graphics Sonic\Walk25",bin,dma_safe
		incfile	Art_Sonic_Walk26,"Graphics Sonic\Walk26",bin,dma_safe
		incfile	Art_Sonic_Walk31,"Graphics Sonic\Walk31",bin,dma_safe
		incfile	Art_Sonic_Walk32,"Graphics Sonic\Walk32",bin,dma_safe
		incfile	Art_Sonic_Walk33,"Graphics Sonic\Walk33",bin,dma_safe
		incfile	Art_Sonic_Walk34,"Graphics Sonic\Walk34",bin,dma_safe
		incfile	Art_Sonic_Walk35,"Graphics Sonic\Walk35",bin,dma_safe
		incfile	Art_Sonic_Walk36,"Graphics Sonic\Walk36",bin,dma_safe
		incfile	Art_Sonic_Walk41,"Graphics Sonic\Walk41",bin,dma_safe
		incfile	Art_Sonic_Walk42,"Graphics Sonic\Walk42",bin,dma_safe
		incfile	Art_Sonic_Walk43,"Graphics Sonic\Walk43",bin,dma_safe
		incfile	Art_Sonic_Walk44,"Graphics Sonic\Walk44",bin,dma_safe
		incfile	Art_Sonic_Walk45,"Graphics Sonic\Walk45",bin,dma_safe
		incfile	Art_Sonic_Walk46,"Graphics Sonic\Walk46",bin,dma_safe
		incfile	Art_Sonic_Run11,"Graphics Sonic\Run11",bin,dma_safe
		incfile	Art_Sonic_Run12,"Graphics Sonic\Run12",bin,dma_safe
		incfile	Art_Sonic_Run13,"Graphics Sonic\Run13",bin,dma_safe
		incfile	Art_Sonic_Run14,"Graphics Sonic\Run14",bin,dma_safe
		incfile	Art_Sonic_Run21,"Graphics Sonic\Run21",bin,dma_safe
		incfile	Art_Sonic_Run22,"Graphics Sonic\Run22",bin,dma_safe
		incfile	Art_Sonic_Run23,"Graphics Sonic\Run23",bin,dma_safe
		incfile	Art_Sonic_Run24,"Graphics Sonic\Run24",bin,dma_safe
		incfile	Art_Sonic_Run31,"Graphics Sonic\Run31",bin,dma_safe
		incfile	Art_Sonic_Run32,"Graphics Sonic\Run32",bin,dma_safe
		incfile	Art_Sonic_Run33,"Graphics Sonic\Run33",bin,dma_safe
		incfile	Art_Sonic_Run34,"Graphics Sonic\Run34",bin,dma_safe
		incfile	Art_Sonic_Run41,"Graphics Sonic\Run41",bin,dma_safe
		incfile	Art_Sonic_Run42,"Graphics Sonic\Run42",bin,dma_safe
		incfile	Art_Sonic_Run43,"Graphics Sonic\Run43",bin,dma_safe
		incfile	Art_Sonic_Run44,"Graphics Sonic\Run44",bin,dma_safe
		incfile	Art_Sonic_Roll1,"Graphics Sonic\Roll1",bin,dma_safe
		incfile	Art_Sonic_Roll2,"Graphics Sonic\Roll2",bin,dma_safe
		incfile	Art_Sonic_Roll3,"Graphics Sonic\Roll3",bin,dma_safe
		incfile	Art_Sonic_Roll4,"Graphics Sonic\Roll4",bin,dma_safe
		incfile	Art_Sonic_Roll5,"Graphics Sonic\Roll5",bin,dma_safe
		incfile	Art_Sonic_Warp1,"Graphics Sonic\Warp1",bin,dma_safe
		incfile	Art_Sonic_Warp2,"Graphics Sonic\Warp2",bin,dma_safe
		incfile	Art_Sonic_Warp3,"Graphics Sonic\Warp3",bin,dma_safe
		incfile	Art_Sonic_Warp4,"Graphics Sonic\Warp4",bin,dma_safe
		incfile	Art_Sonic_Stop1,"Graphics Sonic\Stop1",bin,dma_safe
		incfile	Art_Sonic_Stop2,"Graphics Sonic\Stop2",bin,dma_safe
		incfile	Art_Sonic_Duck,"Graphics Sonic\Duck",bin,dma_safe
		incfile	Art_Sonic_Balance1,"Graphics Sonic\Balance1",bin,dma_safe
		incfile	Art_Sonic_Balance2,"Graphics Sonic\Balance2",bin,dma_safe
		incfile	Art_Sonic_Float1,"Graphics Sonic\Float1",bin,dma_safe
		incfile	Art_Sonic_Float2,"Graphics Sonic\Float2",bin,dma_safe
		incfile	Art_Sonic_Float3,"Graphics Sonic\Float3",bin,dma_safe
		incfile	Art_Sonic_Float4,"Graphics Sonic\Float4",bin,dma_safe
		incfile	Art_Sonic_Spring,"Graphics Sonic\Spring",bin,dma_safe
		incfile	Art_Sonic_Hang1,"Graphics Sonic\Hang1",bin,dma_safe
		incfile	Art_Sonic_Hang2,"Graphics Sonic\Hang2",bin,dma_safe
		incfile	Art_Sonic_Leap1,"Graphics Sonic\Leap1",bin,dma_safe
		incfile	Art_Sonic_Leap2,"Graphics Sonic\Leap2",bin,dma_safe
		incfile	Art_Sonic_Push1,"Graphics Sonic\Push1",bin,dma_safe
		incfile	Art_Sonic_Push2,"Graphics Sonic\Push2",bin,dma_safe
		incfile	Art_Sonic_Push3,"Graphics Sonic\Push3",bin,dma_safe
		incfile	Art_Sonic_Push4,"Graphics Sonic\Push4",bin,dma_safe
		incfile	Art_Sonic_Surf,"Graphics Sonic\Surf",bin,dma_safe
		incfile	Art_Sonic_BubStand,"Graphics Sonic\BubStand",bin,dma_safe
		incfile	Art_Sonic_Burnt,"Graphics Sonic\Burnt",bin,dma_safe
		incfile	Art_Sonic_Drown,"Graphics Sonic\Drown",bin,dma_safe
		incfile	Art_Sonic_Death,"Graphics Sonic\Death",bin,dma_safe
		incfile	Art_Sonic_Shrink1,"Graphics Sonic\Shrink1",bin,dma_safe
		incfile	Art_Sonic_Shrink2,"Graphics Sonic\Shrink2",bin,dma_safe
		incfile	Art_Sonic_Shrink3,"Graphics Sonic\Shrink3",bin,dma_safe
		incfile	Art_Sonic_Shrink4,"Graphics Sonic\Shrink4",bin,dma_safe
		incfile	Art_Sonic_Shrink5,"Graphics Sonic\Shrink5",bin,dma_safe
		incfile	Art_Sonic_Float5,"Graphics Sonic\Float5",bin,dma_safe
		incfile	Art_Sonic_Float6,"Graphics Sonic\Float6",bin,dma_safe
		incfile	Art_Sonic_Injury,"Graphics Sonic\Injury",bin,dma_safe
		incfile	Art_Sonic_GetAir,"Graphics Sonic\GetAir",bin,dma_safe
		incfile	Art_Sonic_WaterSlide,"Graphics Sonic\WaterSlide",bin,dma_safe
